# fly.toml app configuration file generated for finance-app-old-pine-206 on 2025-04-01T12:04:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "finance-app-old-pine-206"
primary_region = "fra"

[build]
  dockerfile = "v02/Dockerfile"

[env]
  STREAMLIT_SERVER_PORT = "8501"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
  DATA_DIR = "/data"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "finance_data"
  destination = "/data"
