version: '3.8'

services:
  finance-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: finance-app
    volumes:
      - ../data:/app/data
    restart: unless-stopped
    networks:
      - finance-network

  nginx:
    image: nginx:alpine
    container_name: finance-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - finance-app
    restart: unless-stopped
    networks:
      - finance-network

  certbot:
    image: certbot/certbot
    container_name: finance-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  finance-network:
    driver: bridge 