# fly.toml app configuration file generated for finance-app-bitter-morning-9768 on 2025-04-01T13:19:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "finance-app-bitter-morning-9768"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  STREAMLIT_SERVER_PORT = "8501"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "rolling"
  release_command = ""

[[mounts]]
  source = "finance_data"
  destination = "/app/data"
