
-- Call the procedures to generate truncate statements
BEGIN
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_activations_seconds;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_energy_bids_and_reserves_seconds;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_prices_and_exchange_rates_seconds;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_activations;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_factor_data;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_energy_bids_and_reserves;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_measurements;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_qualifications;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_prices_and_exchanges;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_schedules;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_operational_state;

    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_availability_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_control_energy_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_settlement_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_settlement_afrr_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_settlement_balancing_energy_bids_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_settlement_mfrr_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_tso_tso_daily;

    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_afrr_balancing_capacity_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_mfrr_balancing_capacity_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_providing_international_assistance_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_using_international_assistance_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_tso_schedule_modification_rir_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_providing_igcc_basic_data_daily;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_providing_multilateral_remedial_action_basic_data_daily;

    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_availability_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_control_energy_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_afrr_balancing_capacity_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_fcr_balancing_capacity_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_mfrr_balancing_capacity_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_u_q_control_reactive_power_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_providing_international_assistance_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_using_international_assistance_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_afrr_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_tso_schedule_modification_rir_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_providing_multilateral_remedial_action_basic_data_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_black_start_service_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_measurements_monthly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_mfrr_monthly;

    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_fcr_balancing_capacity_hourly;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_schedules_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_spectrum_data_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_spectrum_data_seconds_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_prices_and_exchange_rates_seconds_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_afrr_seconds_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_activation_second_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_mfrr_seconds_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_preparation_settlement_qh;
    PAVEL_STRITESKY_METADATA_TRUNCATES.generate_truncate_statements_energy_bids_and_reserves_seconds_qh;
END;
/
